num1 = int(input("enter value"))
num2 = int(input("enter value"))
print("before swapping num1 =",num1)
print("before swapping num2 = ",num2)
(num1,num2)=(num2,num1)
print("num1 = ",num1)
print("num2 = ",num2)